### ISSUE TITLE
DORotate about X-axis wobbles about X, Y, Z axes

### ISSUE THREAD

**Issue by Fuzionist1** [Demigiant/dotween#353]
This is a repost/revision of closed issue #347 because it was closed prematurely.  I have updated my explanation with a simpler example that shows there is clearly a bug in the DORotate method.  

To reproduce the bug:

1. Create a New Unity Project (in Unity 2019.2.10f1)
2. Import the latest version of DOTween Pro (v.1.0.165)
3. Right Click > 3D Object > Cube
4. Cube > Transform > Right Click > Reset
5. Drag CubeRotator onto Cube (see **new code** below)
6. Play

```
using DG.Tweening;
using UnityEngine;

public class CubeRotator : MonoBehaviour
{
    private void Start()
    {
        transform.eulerAngles = new Vector3(95, 0, 0);
        transform.DORotate(
            new Vector3(100, 0, 0), 1);
    }
}
```

**EXPECTED BEHAVIOR:** The cube rotates from X-Rotation of 95 degrees to X-Rotation of 100 degrees, and the Y and Z Rotation values stay at 0 the whole time. 

**ACTUAL BEHAVIOR:** The cube rotates from X-Rotation of 95 degrees to X-Rotation of 100 degrees, and the Y and Z Rotations change constantly throughout the tween.  

**Watch a video here:** https://gfycat.com/zealousdisloyalgallinule
(when viewing, click the gear icon to switch to HD)

I made posts about my experiments here:
https://forum.unity.com/posts/5104151/
https://forum.unity.com/posts/5110205/

![ZealousDisloyalGallinule-size_restricted](https://user-images.githubusercontent.com/13238025/70926147-9593d500-1ffa-11ea-95e4-2805e862b5fd.gif)

**Previous Response**
On Issue #347 there was a response from @lordlycastle that the solution was simply to use RotateMode.LocalAxisAdd.  This is not a solution. 

First, the problem was not the RotateMode.  There was no reason why the Y and Z axes should have changed when only tweening the X-Rotation value.  

Second, RotateMode.LocalAxisAdd is a different method used for different circumstances.  It does not allow you to choose the final rotation angle.  It adds to whatever the current rotation angle may be.  This is not the behavior I needed, and this does not correct the bug in the DORotate method. 

**FURTHER COMMENTS**
My investigations have revealed that the bug described appears to happen only when the starting X-Rotation is greater than 90 degrees - and only happens with X-Rotation (not with Y-Rotation or Z-Rotation).  

**Example 1** - Rotation-X from 70 degrees to 80 degrees:
```
using DG.Tweening;
using UnityEngine;

public class CubeRotator : MonoBehaviour
{
    private void Start()
    {
        transform.eulerAngles = new Vector3(70, 0, 0);
        transform.DORotate(
            new Vector3(80, 0, 0), 1);
    }
}
```

Notice in the video that the X-Rotation tweens from 70 to 80 degrees, **while the Y and Z remain at 0 the entire time**.  This is correct behavior. 

Video: https://gfycat.com/recklessdownrightenglishsetter 
![RecklessDownrightEnglishsetter-size_restricted](https://user-images.githubusercontent.com/13238025/70927057-49499480-1ffc-11ea-93bf-6f65148b8142.gif)

**Example 2** - Rotation Y from 95 degrees to 100 degrees:

```
using DG.Tweening;
using UnityEngine;

public class CubeRotator : MonoBehaviour
{
    private void Start()
    {
        transform.eulerAngles = new Vector3(0, 95, 0);
        transform.DORotate(
            new Vector3(0, 100, 0), 1);
    }
}
```

Notice in the video that the Y-Rotation tweens from 95 to 100 degrees, **while the X and Z remain at 0 the entire time**.  This is correct behavior.

Video: https://gfycat.com/kaleidoscopicglaringdormouse
![KaleidoscopicGlaringDormouse-size_restricted](https://user-images.githubusercontent.com/13238025/70927362-d42a8f00-1ffc-11ea-9bcf-b44afe28d4f0.gif)

**CONCLUSION**
The DORotate method has a bug characterized by wobbling in the Y and Z axes when rotating about the X axis starting from an X-Rotation angle above 90 degrees.

**Comment by lordlycastle** [comment]
@Demigiant thought? Curious to know this behavior as well.

My reasoning for previous issues was that when you move from `180, 0, 0` to `0/360, 0, 0` and take `FastBeyond360` mode, it does the right behavior where it rotates all axes as that is the fastest way to get to that rotation. I assumed that was only true when you were moving back to 0/ 360; I would not expect this to happen if you moved to 359.

**Comment by Demigiant** [comment]
Ahoy! Mhmmm that is indeed weird. Testing this out :P

**Comment by Demigiant** [comment]
Oh, all clear now. The problem is that the euler value of a Quaternion is not really the same Vector3 value that the Unity inspector shows you (100,0,0 is actually 80,180,180) and in some cases it makes the rotation behave weirdly. This can be solved by using DORotateQuaternion instead, but I'm implementing a fix for the normal DORotate (I already have it working, but since it changes the core system of how rotations work I want to test it out a little bit more).

**Comment by Fuzionist1** [comment]
Hi @Demigiant , if you take a look at my forum posts (links provided above), you will see code and video showing an example where I clicked Flip To Back - rotating X to 180, then I clicked Flip To Back again (which should do nothing because the angle is already 180) and the object wobbles dramatically about all axes. This behavior can likely be reproduced for any X angle above 90. And this behavior is specific to X axis. In fact my temporary fix was to rotate my artwork 90 degrees so I could use DORotate on an axis other than X.

**Comment by Demigiant** [comment]
The fix I made should fix everything :) Though it's taking me much more to create a comprehensive test (also for Beyond360 and From tweens) than the time it took me to implement the fix :B

**Comment by Fuzionist1** [comment]
Thank you. :)

**Comment by lordlycastle** [comment]
@Demigiant Live a little. *If you have no tests, then they cannot fail.*  💯

**Comment by Demigiant** [comment]
Whew, it's more time-consuming than I thought. I have to stop now but I'll continue tomorrow (problem is now from 85 to 100, thought 180 to 180 works correctly) :P The GIF is for the Fast RotateMode.

![dotweenRotateTests](https://user-images.githubusercontent.com/8322877/71101202-940f0c00-21b6-11ea-85a7-15914bf83e2c.gif)

**Comment by Fuzionist1** [comment]
Thanks @Demigiant   I appreciate your efforts to resolve this. I am a pretty new adopter of DOTween, but I cannot imagine that others have not also faced this issue and will appreciate your work to fix it. Cheers.

**Comment by Fuzionist1** [comment]
Just checking to see if there is an update on this.  (FYI - I have supported by purchasing DoTween Pro). Thanks!

**Comment by Demigiant** [comment]
I postponed this in favor of [this craziness](https://twitter.com/demigiant/status/1219226110338248704). I hope using DORotateQuaternion in the meantime is good enough for you, but I'll get back to it asap (sorry for the delay).

**Comment by lordlycastle** [comment]
@Demigiant Hot Damn! That's whack! Love it. Would be possible to do callback through UI as well?

It would be kewl if it can generate the code too. 

I had some performance question, where should I ask them?

**Comment by Demigiant** [comment]
It will definitely allow callback within the UI but will not generate code :P

About performance, open a new issue and I'll check it within the day, promised! :)

**Comment by Fuzionist1** [comment]
Thanks for the update. And that graphical UI looks awesome.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jmdodge** [comment]
+1 for this issue. I thought I was completely losing my mind until I came across this.

I'm not sure if DoRotateQuaternion is an adequate workaround - it seems to behave differently than my other rotate tweens, at least with regard to speed (I'm using .SetSpeedBased() - does DoRotateQuaternion support that?).  Maybe I could convert all of my rotation tweens to quaternions so the speeds would be unified just so this one wouldn't be broken, but then it seems like calculation for all their angles would be more difficult, since most times I'm using  simple manipulation of euler angles to get my rotations.

Crossing my fingers for a fix in the near future :)

**Comment by Demigiant** [comment]
As soon as I'm done with the Timeline I'll get back to this. I already have nightmares :P

**Comment by piyushradadiya** [comment]
> This is a repost/revision of closed issue #347 because it was closed prematurely. I have updated my explanation with a simpler example that shows there is clearly a bug in the DORotate method.
> 
> To reproduce the bug:
> 
> 1. Create a New Unity Project (in Unity 2019.2.10f1)
> 2. Import the latest version of DOTween Pro (v.1.0.165)
> 3. Right Click > 3D Object > Cube
> 4. Cube > Transform > Right Click > Reset
> 5. Drag CubeRotator onto Cube (see **new code** below)
> 6. Play
> 
> ```
> using DG.Tweening;
> using UnityEngine;
> 
> public class CubeRotator : MonoBehaviour
> {
>     private void Start()
>     {
>         transform.eulerAngles = new Vector3(95, 0, 0);
>         transform.DORotate(
>             new Vector3(100, 0, 0), 1);
>     }
> }
> ```
> 
> **EXPECTED BEHAVIOR:** The cube rotates from X-Rotation of 95 degrees to X-Rotation of 100 degrees, and the Y and Z Rotation values stay at 0 the whole time.
> 
> **ACTUAL BEHAVIOR:** The cube rotates from X-Rotation of 95 degrees to X-Rotation of 100 degrees, and the Y and Z Rotations change constantly throughout the tween.
> 
> **Watch a video here:** https://gfycat.com/zealousdisloyalgallinule
> (when viewing, click the gear icon to switch to HD)
> 
> I made posts about my experiments here:
> https://forum.unity.com/posts/5104151/
> https://forum.unity.com/posts/5110205/
> 
> ![ZealousDisloyalGallinule-size_restricted](https://user-images.githubusercontent.com/13238025/70926147-9593d500-1ffa-11ea-95e4-2805e862b5fd.gif)
> 
> **Previous Response**
> On Issue #347 there was a response from @lordlycastle that the solution was simply to use RotateMode.LocalAxisAdd. This is not a solution.
> 
> First, the problem was not the RotateMode. There was no reason why the Y and Z axes should have changed when only tweening the X-Rotation value.
> 
> Second, RotateMode.LocalAxisAdd is a different method used for different circumstances. It does not allow you to choose the final rotation angle. It adds to whatever the current rotation angle may be. This is not the behavior I needed, and this does not correct the bug in the DORotate method.
> 
> **FURTHER COMMENTS**
> My investigations have revealed that the bug described appears to happen only when the starting X-Rotation is greater than 90 degrees - and only happens with X-Rotation (not with Y-Rotation or Z-Rotation).
> 
> **Example 1** - Rotation-X from 70 degrees to 80 degrees:
> 
> ```
> using DG.Tweening;
> using UnityEngine;
> 
> public class CubeRotator : MonoBehaviour
> {
>     private void Start()
>     {
>         transform.eulerAngles = new Vector3(70, 0, 0);
>         transform.DORotate(
>             new Vector3(80, 0, 0), 1);
>     }
> }
> ```
> 
> Notice in the video that the X-Rotation tweens from 70 to 80 degrees, **while the Y and Z remain at 0 the entire time**. This is correct behavior.
> 
> Video: https://gfycat.com/recklessdownrightenglishsetter
> ![RecklessDownrightEnglishsetter-size_restricted](https://user-images.githubusercontent.com/13238025/70927057-49499480-1ffc-11ea-93bf-6f65148b8142.gif)
> 
> **Example 2** - Rotation Y from 95 degrees to 100 degrees:
> 
> ```
> using DG.Tweening;
> using UnityEngine;
> 
> public class CubeRotator : MonoBehaviour
> {
>     private void Start()
>     {
>         transform.eulerAngles = new Vector3(0, 95, 0);
>         transform.DORotate(
>             new Vector3(0, 100, 0), 1);
>     }
> }
> ```
> 
> Notice in the video that the Y-Rotation tweens from 95 to 100 degrees, **while the X and Z remain at 0 the entire time**. This is correct behavior.
> 
> Video: https://gfycat.com/kaleidoscopicglaringdormouse
> ![KaleidoscopicGlaringDormouse-size_restricted](https://user-images.githubusercontent.com/13238025/70927362-d42a8f00-1ffc-11ea-9bcf-b44afe28d4f0.gif)
> 
> **CONCLUSION**
> The DORotate method has a bug characterized by wobbling in the Y and Z axes when rotating about the X axis starting from an X-Rotation angle above 90 degrees.

any updates on this?

**Comment by lordlycastle** [comment]
@piyushradadiya lol.... dat quote dough! 🍞

**Comment by shravanvavadiya** [comment]
I've been following this thread recently, and waiting for it to get solved.
@Demigiant Do you have any update on this? Also if there is any workaround for it?

Thanks

**Comment by Demigiant** [comment]
Ahoy! I postponed this more and more in favor of other things (but at times tried a couple other solutions but they didn't work), I apologize (last new thing that "ate" this one is a way to tween TMP texts per-character including skew/scale/shift, so pros and cons I hope).

The current workaround is to use DORotateQuaternion instead (will add it to the docs until I fix this):
```
transform.eulerAngles = new Vector3(95, 0, 0);
transform.DORotateQuaternion(Quaternion.Euler(new Vector3(100, 0, 0)), 1);
```

**Comment by shravanvavadiya** [comment]
Yay! That worked.
Thanks for the help!

**Comment by mmeiburg** [comment]
@Demigiant Hi hope you'll have some time to dig into this issue again.

Until then I wish you all the best. Stay safe and healthy ...happy holidays.

**Comment by violeDgrace** [comment]
i know its very late, but i had the same problem. used transform.DOLocalRotate(Vector3 , 1);

**Comment by Rohith-Nanthan** [comment]
Hi @Demigiant , I am also facing the issue for Do Local Rotate. Every time I try to align using do tween the destination keeps changing.
```
  private Tween GetRotateTween(AnimData data)
  {
      var curretAngle = data.targetMesh.localRotation.eulerAngles;
      return data.targetMesh.DOLocalRotate(new Vector3( data.xAngle,curretAngle.y,curretAngle.z) , data.time);
  }
```
I want to rotate the mesh to a fixed angle in its local axis but the result is not as expected at all times. It rotates beyond the desired angle sometimes. Please resolve this ASAP 🙏

**Comment by Rohith-Nanthan** [comment]
@Demigiant , I also tried Do local Rotate Quaternion but it still doesn't work 😢
```
    private Tween GetRotateTween(AnimData data)
    {
        var curretAngle = data.targetMesh.localRotation.eulerAngles;
        return data.targetMesh.DOLocalRotateQuaternion( Quaternion.Euler(new Vector3( data.xAngle,curretAngle.y,curretAngle.z)) , data.time);
        //return data.targetMesh.DOLocalRotate(new Vector3( data.xAngle,curretAngle.y,curretAngle.z) , data.time);
    }
```

**Comment by Demigiant** [comment]
Ouch, DOLocalRotateQuaternion not working makes this an emergency. On it during this week, sorry!

**Comment by Demigiant** [comment]
Whew. Ok I'm tapped out (spent all week working on this, and all this morning making tests). [This new version (1.2.675)](http://dotween.demigiant.com/tmp/DOTween_1_2_675_unity567.zip) fixes the problem with RotateMode.Fast, but still has the same problem with RotateMode.Beyond360 and from/relative tweens. I will get to those later but for now it's the right replacement for DORotateQuaternion not working correctly (or better: working correctly in Unity's Quaternion space but not in what one usually wants as an actual result)

**Comment by Rohith-Nanthan** [comment]
Hi, Thanks for pushing the update in the short time I really appreciate it. I tested the new build and unfortunately it still doesn't resolve DoLocalRotate with RotateMode.Fast or with DoLocalRotateQuartenion 😢

**Comment by Demigiant** [comment]
What?!? Agh! But! I made tons of tests with various kinds of starting and ending rotations, noooo :( So sorry, I thought I had at least fixed this side of it. Could you post me a sample code with the actual starting rotation and final rotation you're using (or even better, a small package that replicates it), so I can test against your case directly?

**Comment by Demigiant** [comment]
Victory! [This update (v1.2.680)](http://dotween.demigiant.com/tmp/DOTween_1_2_680_unity567.zip) fixes the wobbling with all methods, including From. I'm leaving the issue open while I test it even more, but with all my tests (including yours, @Rohith-Nanthan) everything works.

**Comment by Fuzionist1** [comment]
Thanks @Demigiant .  I appreciate you getting around to this.

**Comment by Demigiant** [comment]
Thank you, IT WAS HELL (and sorry it took so long) :D (Because Unity and Quaternions are not really made to be animated on a single axis and "wobble" is the intended behaviour, but glad that I managed to hack it :))

**Comment by Rohith-Nanthan** [comment]
Hi @Demigiant . Thanks for sharing the quick update. I tested it and yes it works for `DOLocalRotateQuaternion` but unfortunately it still wobbles for `DOLocalRotate`. Anyways, thanks for the quick fix man. I really appreciate your effort. 🙏

**Comment by Demigiant** [comment]
Ahoy @Rohith-Nanthan! But did you read my mail? Because in your code there were other issues causing the wobble, and when I solved them in my repro it seemed to be working

**Comment by gakkossphynx** [comment]
Hello How Can i use .DoLocalRotate Without Integrating DG.Tweening Namespace At All ?

**Comment by devilpig** [comment]
Hello! Just chipping in on this :) 
The bug seems to still exist in the latest version (1.0.335). I updated the plugin yesterday and noticed this happening when using:
`transform.DOLocalRotate(new Vector3(rotationValue, 0, 0), duration, RotateMode.LocalAxisAdd);`
where rotationValue is 90 each time around.

**Comment by Demigiant** [comment]
Ahoy! It happens also with WorldAxisAdd (sorryyyy). [This fix](http://dotween.demigiant.com/tmp/DOTween_1_2_710_unity567.zip) should fix it for real (I quadruple-checked and my rotation test scene is now full of dices doing all possible rotations and rotation modes nicely).

P.S. It's only DOTween's core but the issue is there, so you can update it while keeping your current Pro version.

**Comment by Demigiant** [comment]
(waiting for an addition to the Pro to be confirmed and then will push it on the asset store this weekend)

**Comment by devilpig** [comment]
Aaaah beautiful! It works \o/
Thank you for the swift response! Keep up the good work!

**Comment by Nyankoo** [comment]
@Demigiant Is the update already live on the Asset Store or still pending?

**Comment by Ayfel** [comment]
Just wanted to chime in and mention this is still happening in some cases and only using DoRotateQuaternion fixes it (I even tried the latest package shared here and same issue)

**Comment by Demigiant** [comment]
@Ayfel Ouch! Could you write me an example code that doesn't work so I can test it out? All my test values work here so I can't reproduce it

**Comment by lordlycastle** [comment]
Thanks for all you hard work @Demigiant! It is appreciated.

**Comment by hellomp** [comment]
Sorry to bring this back to life but I'm having issues with this as well even using the latest DOTween version (DOTween 1.2.745, DOTWeen Pro 1.0.375). Here is how the object rotation is when starting the scene:
![image](https://github.com/Demigiant/dotween/assets/10708618/e10765dc-c18e-4617-9bad-50c855a5bba8)
And here is how it ends up after a couple of turns (It happens after the first X rotation and then it accumulates from there):
![image](https://github.com/Demigiant/dotween/assets/10708618/ad9df6a0-2cb8-442c-9d0d-a48429e47730)
Here is the code I'm using:

    public class DOTweenProblem : MonoBehaviour
    {
        [SerializeField] private bool _rotating;

        void Update()
        {
            if (_rotating)
                return;
            if (Input.GetKeyDown(KeyCode.A))
                StartRotatingY(-90f);
            if (Input.GetKeyDown(KeyCode.D))
                StartRotatingY(90f);
            if (Input.GetKeyDown(KeyCode.W))
                StartRotatingX(90f);
            if (Input.GetKeyDown(KeyCode.S))
                StartRotatingX(-90f);
        }

        public void StartRotatingY(float angle)
        {
            _rotating = true;
            transform.DORotate(new Vector3(transform.rotation.x, angle, transform.rotation.z), .2f, RotateMode.WorldAxisAdd).SetRelative(true).OnComplete(EndRotating);
        }

        public void StartRotatingX(float angle)
        {
            _rotating = true;
            transform.DORotate(new Vector3(angle, transform.rotation.y, transform.rotation.z), .2f, RotateMode.WorldAxisAdd).SetRelative(true).OnComplete(EndRotating);

        }

        public void EndRotating()
        {
            _rotating = false;
        }
    }
